import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function renderBusinessPdf({
  title,
  subtitle,
  rows,
  total,
}: {
  title: string;
  subtitle: string;
  rows: Array<[string, string]>;
  total?: string;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const navy = rgb(0.043, 0.122, 0.227);
  const blue = rgb(0.145, 0.388, 0.922);
  const grey = rgb(0.38, 0.45, 0.55);

  page.drawText("AI AutoTech", { x: 48, y: 780, size: 20, font: bold, color: navy });
  page.drawText(title, { x: 48, y: 736, size: 28, font: bold, color: navy });
  page.drawText(subtitle, { x: 48, y: 712, size: 11, font: regular, color: grey });
  page.drawLine({ start: { x: 48, y: 690 }, end: { x: 547, y: 690 }, thickness: 1, color: rgb(0.86, 0.89, 0.93) });

  let y = 650;
  rows.forEach(([label, value]) => {
    page.drawText(label, { x: 48, y, size: 11, font: bold, color: navy });
    page.drawText(value, { x: 230, y, size: 11, font: regular, color: rgb(0.05, 0.09, 0.16) });
    y -= 30;
  });

  if (total) {
    page.drawRectangle({ x: 48, y: y - 16, width: 499, height: 48, color: rgb(0.94, 0.97, 1) });
    page.drawText("Total", { x: 66, y: y + 2, size: 12, font: bold, color: navy });
    page.drawText(total, { x: 430, y: y + 2, size: 16, font: bold, color: blue });
  }

  page.drawText("Generated by AI AutoTech", { x: 48, y: 48, size: 9, font: regular, color: grey });

  return pdf.save();
}
